dependencies:
- name: common
  version: 0.0.1
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
- name: catalogue
  version: 0.3.5-master
  condition: catalogue.enabled, global.catalogue.enabled
  repository: "@cloudpossedemo"
