name: build-push

on:
  push:
    branches: [ master ]

jobs:
  test-build:
    # if: ${{ false }}  # disable
    runs-on: ubuntu-latest
    env:
      GROUP: uoyak 
      COMMIT: ${{ github.sha }}
      REPO: dtst-sockshop-front-end
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '4.x'

    - run: npm install

    - name: Test image
      env:
        DOCKER_BUILDKIT: 1
      run: make test

    - name: Build docker image
      uses: docker/build-push-action@v1
      with:
        push: false
        repository: ${{ env.GROUP }}/${{ env.REPO }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}

    - name: Test docker image
      env:
        DOCKER_BUILDKIT: 1
      run: ./test/container.sh
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Set image tag
      id: set-tag
      run: |
        echo ${{ github.sha }}
        ls -l
        id=$(echo sha-${{ github.sha }} | cut -c 1-11)
        echo "id=$id" >> $GITHUB_OUTPUT

    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      # if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
      with:
        push: true
        tags: ${{ env.GROUP }}/${{ env.REPO }}:${{ steps.set-tag.outputs.id }}
        # repository: ${{ env.GROUP }}/${{ env.REPO }}
        # tag_with_ref: true
        # tag_with_sha: true