name: trigger-deploy
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: "Choose environnement"
        default: prod
        options:
        - dev
        - prod
      sha:
        description: "Enter Sha"
        default: "sha-ae479a0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow to deploy front-end
        # run: |
        #   curl -X POST https://api.github.com/repos/Uoyak/dtst-sockshop/actions/workflows/deploy-front-end.yaml/dispatches \
        #   -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
        #   -H "Accept: application/vnd.github.everest-preview+json" \
        #   -H "Content-Type: application/json" \
        #   --data '{"ref": "master", "inputs": { "name": "${{ inputs.environnement }}", "sha": "${{ github.sha }}" }}'
        run: |
          curl -X POST https://api.github.com/repos/Uoyak/dtst-sockshop/actions/workflows/deploy-front-end.yaml/dispatches \
          -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github+json" \
          -H "Content-Type: application/json" \
          --data '{"ref": "master", "inputs": { "env": "${{ inputs.env }}", "sha": "${{ github.sha }}" }}'

